/*
 * OreVeins - ore vein generation for Paper/Purpur
 * Copyright (C) 2014 Kevin Mendoza
 * Copyright (C) 2026 Esoren
 * SPDX-License-Identifier: GPL-2.0-or-later
 */
package com.icloud.kevinmendoza.oreveins;

import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertFalse;
import static org.junit.jupiter.api.Assertions.assertTrue;

import com.google.gson.JsonArray;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import java.util.List;
import java.util.logging.Logger;
import org.bukkit.Material;
import org.bukkit.World;
import org.bukkit.configuration.file.YamlConfiguration;
import org.junit.jupiter.api.Test;

class WebModelTest {
    private static final List<WebModel.WorldView> VANILLA = List.of(
            new WebModel.WorldView("world", World.Environment.NORMAL, -64, 320),
            new WebModel.WorldView("world_nether", World.Environment.NETHER, 0, 256),
            new WebModel.WorldView("world_the_end", World.Environment.THE_END, 0, 256));

    private static GeneratorSettings defaults() {
        return GeneratorSettings.load(GeneratorSettingsTest.resource(ConfigFiles.DEFAULT_RESOURCE),
                Logger.getAnonymousLogger());
    }

    private static JsonObject pass(JsonObject world, String id) {
        for (JsonElement element : world.getAsJsonArray("passes")) {
            if (element.getAsJsonObject().get("id").getAsString().equals(id)) {
                return element.getAsJsonObject();
            }
        }
        throw new AssertionError("no pass " + id);
    }

    @Test
    void guideListsEnabledOverworldAndNetherWorldsWithTheirPasses() {
        GeneratorSettings settings = defaults();
        JsonObject guide = WebModel.guide(settings, VANILLA);
        JsonArray worlds = guide.getAsJsonArray("worlds");
        assertEquals(2, worlds.size(), "the End is never generated by OreVeins");
        JsonObject overworld = worlds.get(0).getAsJsonObject();
        assertEquals("world", overworld.get("name").getAsString());
        assertEquals(-64, overworld.get("minY").getAsInt());
        assertEquals(319, overworld.get("maxY").getAsInt());
        long normalPasses = settings.veins().stream().filter(v -> v.environment() == World.Environment.NORMAL).count();
        assertEquals(normalPasses, overworld.getAsJsonArray("passes").size());
        assertTrue(guide.get("replaceExisting").getAsBoolean());

        VeinDefinition coal = settings.veins().stream().filter(v -> v.id().equals("coal-upper")).findFirst().orElseThrow();
        JsonObject coalJson = pass(overworld, "coal-upper");
        assertEquals("coal", coalJson.get("ore").getAsString());
        assertEquals("minecraft:coal_ore", coalJson.get("material").getAsString());
        assertEquals("minecraft:deepslate_coal_ore", coalJson.get("deepslateMaterial").getAsString());
        assertEquals(coal.minY(), coalJson.get("minY").getAsInt(), "vanilla world = reference height");
        assertEquals(coal.maxY(), coalJson.get("maxY").getAsInt());
        assertEquals(coal.attemptsPerChunk() * coal.spawnChance() * coal.size(),
                coalJson.get("blocksPerChunk").getAsDouble(), 0.001);
        assertTrue(coalJson.get("active").getAsBoolean());
        assertTrue(coalJson.get("regenerable").getAsBoolean());

        JsonObject nether = worlds.get(1).getAsJsonObject();
        assertEquals("NETHER", nether.get("environment").getAsString());
        for (JsonElement element : nether.getAsJsonArray("passes")) {
            assertFalse(element.getAsJsonObject().get("ore").getAsString().isEmpty());
        }
    }

    @Test
    void guideScalesYRangesToTallWorldsLikeTheGenerator() {
        GeneratorSettings settings = defaults();
        WebModel.WorldView tall = new WebModel.WorldView("tall", World.Environment.NORMAL, -256, 512);
        JsonObject world = WebModel.guide(settings, List.of(tall)).getAsJsonArray("worlds").get(0).getAsJsonObject();
        HeightReference reference = settings.heightReferences().get(World.Environment.NORMAL);
        for (VeinDefinition vein : settings.veins()) {
            if (vein.environment() != World.Environment.NORMAL) {
                continue;
            }
            JsonObject json = pass(world, vein.id());
            assertEquals(VeinPopulator.scaledMinY(reference, vein, -256, 512), json.get("minY").getAsInt());
            assertEquals(VeinPopulator.scaledMaxY(reference, vein, -256, 512), json.get("maxY").getAsInt());
            assertTrue(json.get("minY").getAsInt() >= -256 && json.get("maxY").getAsInt() <= 511);
        }
    }

    @Test
    void guideRespectsEnabledWorlds() {
        YamlConfiguration config = GeneratorSettingsTest.resource(ConfigFiles.DEFAULT_RESOURCE);
        config.set("settings.enabled-worlds", List.of("World_Nether"));
        GeneratorSettings settings = GeneratorSettings.load(config, Logger.getAnonymousLogger());
        JsonArray worlds = WebModel.guide(settings, VANILLA).getAsJsonArray("worlds");
        assertEquals(1, worlds.size());
        assertEquals("world_nether", worlds.get(0).getAsJsonObject().get("name").getAsString());
    }

    @Test
    void oreFamiliesDropDeepslateAndOreSuffix() {
        assertEquals("iron", WebModel.family(Material.DEEPSLATE_IRON_ORE));
        assertEquals("nether_quartz", WebModel.family(Material.NETHER_QUARTZ_ORE));
        assertEquals("ancient_debris", WebModel.family(Material.ANCIENT_DEBRIS));
        assertEquals("magma_block", WebModel.family(Material.MAGMA_BLOCK));
        assertEquals("lava", WebModel.family(Material.LAVA));
    }

    @Test
    void statusCarriesCountersCampaignAndLastScan() {
        GeneratorSettings settings = defaults();
        JsonObject idle = WebModel.status(new WebModel.StatusView(settings, true, "auto",
                10, 2, 0, false, false, 0, 0, 0.0, null));
        assertEquals(28, idle.get("passes").getAsInt());
        assertTrue(idle.get("legacyConfig").getAsBoolean());
        assertTrue(idle.get("chunksPerMinute").isJsonNull());
        assertTrue(idle.get("lastScan").isJsonNull());
        assertFalse(idle.getAsJsonObject("campaign").get("active").getAsBoolean());
        assertEquals(AdminActions.MAX_RADIUS, idle.get("maxRadius").getAsInt());

        JsonObject running = WebModel.status(new WebModel.StatusView(settings, false, "de",
                500, 0, 1200, false, true, 480, 1180, 47.26,
                new AdminActions.ScanReport(2, 2000, 1200, 1, 1234L)));
        assertEquals(47.3, running.get("chunksPerMinute").getAsDouble(), 1e-9);
        assertEquals(480, running.getAsJsonObject("campaign").get("done").getAsInt());
        assertEquals(1180, running.getAsJsonObject("campaign").get("remaining").getAsInt());
        assertEquals(2000, running.getAsJsonObject("lastScan").get("found").getAsInt());
    }

    @Test
    void actionAnswersUseTheCommandTextsWithoutPrefix() {
        Messages messages = Messages.bundled("auto");
        JsonObject answer = WebModel.outcome(AdminActions.queued(0), messages, "de");
        assertTrue(answer.get("ok").getAsBoolean());
        JsonArray lines = answer.getAsJsonArray("messages");
        assertEquals(2, lines.size());
        assertEquals(messages.plain("de", "regenerate.queued", "count", 0), lines.get(0).getAsString());
        assertFalse(lines.get(0).getAsString().startsWith("["));
        JsonObject refused = WebModel.outcome(AdminActions.Outcome.failed(
                new AdminActions.Line("regenerate.all.already-running")), messages, "en");
        assertFalse(refused.get("ok").getAsBoolean());
        assertEquals("An all-chunk scan is already running.", refused.getAsJsonArray("messages").get(0).getAsString());
    }
}
